[separator]
cmd = "NULL"
icon = "nemo-vertical-layout-wide-symbolic"


[firefox-developer-edition]
cmd = "/usr/lib/firefox-developer-edition/firefox"
icon = "firefox-developer-edition"

[hbomax]
cmd = "mullvad-exclude gtk-launch msedge-dinihlfpipipfkcmaaepepiogdhoflhb-Default"
icon = "msedge-dinihlfpipipfkcmaaepepiogdhoflhb-Default"

[prime]
cmd = "mullvad-exclude gtk-launch msedge-kmifndnklcjngpikicihnhfmmfhpkcii-Default.desktop"
icon = "chrome-nbkkgiflglejhikcliinbkikeklbpppp-Default"

[disney]
cmd = "mullvad-exclude gtk-launch msedge-clbjnikbacibakcglofhpmppkpcmkacd-Default"
icon = "msedge-clbjnikbacibakcglofhpmppkpcmkacd-Default"

[starplus]
cmd = "mullvad-exclude gtk-launch msedge-bpjcodegpiniicldnepnkignejinkjpk-Default"
icon = "msedge-bpjcodegpiniicldnepnkignejinkjpk-Default"

[steam]
cmd = "mullvad-exclude steam"
icon = "steam"

[code]
cmd = "code"
icon = "code"

[thunderbird]
cmd = "thunderbird"
icon = "thunderbird"

[telegram]
cmd = "telegram-desktop"
icon = "telegram-desktop"

[hexchat]
cmd = "hexchat"
icon = "hexchat"

[thunar]
cmd = "thunar"
icon = "thunar"

[gnome-terminal]
cmd = "gnome-terminal"
icon = "gnome-terminal"

[chromium]
cmd = "/usr/lib/chromium/chromium"
icon = "chromium"

[kitty]
cmd = "/usr/bin/kitty"
icon = "kitty"
