[icons]
"System" = "system-shutdown-alt3"

[[System.item_1]]
cmd = "hyprctl dispatch exit"
name = "Logout"

[[System.item_2]]
cmd = "reboot"
name = "Reiniciar"


[[System.shutdown_now]]
cmd = "shutdown -h now"
name = "Desligar PC"


[[System.item_3]]
cmd = "hyprctl keyword monitor DP-1, disable;hyprpanel"
name = "Desligar monitor da direita"

[[System.item_4]]
cmd = "hyprctl keyword monitor DP-2, disable;hyprpanel"
name = "Desligar Monitor da esquerda"

[[System.item_5]]
cmd = "hyprctl reload; killall -9 hyprpanel;hyprpanel"
name = "Religar Monitores"

[[System.item_6]]
cmd = "killall -9 python3 /usr/bin/hyprpanel"
name = "Fechar Hyprpanel"
