[workspace_8]
cmd = "hyprctl dispatch hyprshell:leaveoverview;hyprctl dispatch workspace 8"
icon = "indicator-workspaces-8"

[workspace_7]
cmd = "hyprctl dispatch hyprshell:leaveoverview;hyprctl dispatch workspace 7"
icon = "indicator-workspaces-7"

[workspace_6]
cmd = "hyprctl dispatch hyprshell:leaveoverview;hyprctl dispatch workspace 6"
icon = "indicator-workspaces-6"

[workspace_5]
cmd = "hyprctl dispatch hyprshell:leaveoverview;hyprctl dispatch workspace 5"
icon = "indicator-workspaces-5"

[workspace_4]
cmd = "hyprctl dispatch hyprshell:leaveoverview;hyprctl dispatch workspace 4"
icon = "indicator-workspaces-4"

[workspace_3]
cmd = "hyprctl dispatch hyprshell:leaveoverview;hyprctl dispatch workspace 3"
icon = "indicator-workspaces-3"

[workspace_2]
cmd = "hyprctl dispatch hyprshell:leaveoverview;hyprctl dispatch workspace 2"
icon = "indicator-workspaces-2"

[workspace_1]
cmd = "hyprctl dispatch hyprshell:leaveoverview;hyprctl dispatch workspace 1"
icon = "indicator-workspaces-1"
